name: Frontend
services:
  frontend:
    container_name: Frontend
    build:
      context: ../app/frontend
      dockerfile: ../../docker/frontend/Dockerfile
    volumes:
      - ../app/frontend:/app
    working_dir: /app
    ports:
      - "80:80"
    command: ["npm", "run", "live"]
